// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Rabbitmq      *RabbitMQ              `protobuf:"bytes,2,opt,name=rabbitmq,proto3" json:"rabbitmq,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Asynq         *Asynq                 `protobuf:"bytes,4,opt,name=asynq,proto3" json:"asynq,omitempty"`
	Log           *Log                   `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	Dcc           *Dcc                   `protobuf:"bytes,6,opt,name=dcc,proto3" json:"dcc,omitempty"`
	Monitor       *Monitor               `protobuf:"bytes,7,opt,name=monitor,proto3" json:"monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetRabbitmq() *RabbitMQ {
	if x != nil {
		return x.Rabbitmq
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAsynq() *Asynq {
	if x != nil {
		return x.Asynq
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetDcc() *Dcc {
	if x != nil {
		return x.Dcc
	}
	return nil
}

func (x *Bootstrap) GetMonitor() *Monitor {
	if x != nil {
		return x.Monitor
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type RabbitMQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     string                 `protobuf:"bytes,1,opt,name=addresses,proto3" json:"addresses,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Listener      *RabbitMQ_Listener     `protobuf:"bytes,5,opt,name=listener,proto3" json:"listener,omitempty"`
	Topic         *RabbitMQ_Topic        `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RabbitMQ) Reset() {
	*x = RabbitMQ{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RabbitMQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RabbitMQ) ProtoMessage() {}

func (x *RabbitMQ) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RabbitMQ.ProtoReflect.Descriptor instead.
func (*RabbitMQ) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *RabbitMQ) GetAddresses() string {
	if x != nil {
		return x.Addresses
	}
	return ""
}

func (x *RabbitMQ) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RabbitMQ) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RabbitMQ) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RabbitMQ) GetListener() *RabbitMQ_Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

func (x *RabbitMQ) GetTopic() *RabbitMQ_Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mysql         *Data_Mysql            `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Etcd          *Etcd                  `protobuf:"bytes,3,opt,name=etcd,proto3" json:"etcd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetMysql() *Data_Mysql {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetEtcd() *Etcd {
	if x != nil {
		return x.Etcd
	}
	return nil
}

type Etcd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Etcd) Reset() {
	*x = Etcd{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Etcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etcd) ProtoMessage() {}

func (x *Etcd) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etcd.ProtoReflect.Descriptor instead.
func (*Etcd) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Etcd) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Etcd) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Dcc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RateLimit     int32                  `protobuf:"varint,1,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`             // 限流阈值
	EnableDegrade bool                   `protobuf:"varint,2,opt,name=enable_degrade,json=enableDegrade,proto3" json:"enable_degrade,omitempty"` // 降级开关
	BlackList     string                 `protobuf:"bytes,3,opt,name=black_list,json=blackList,proto3" json:"black_list,omitempty"`              // 黑名单 (对应你 yaml 里的字符串)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dcc) Reset() {
	*x = Dcc{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dcc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dcc) ProtoMessage() {}

func (x *Dcc) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dcc.ProtoReflect.Descriptor instead.
func (*Dcc) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Dcc) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

func (x *Dcc) GetEnableDegrade() bool {
	if x != nil {
		return x.EnableDegrade
	}
	return false
}

func (x *Dcc) GetBlackList() string {
	if x != nil {
		return x.BlackList
	}
	return ""
}

type Asynq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redis         *Asynq_Redis           `protobuf:"bytes,1,opt,name=redis,proto3" json:"redis,omitempty"`
	Concurrency   int32                  `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asynq) Reset() {
	*x = Asynq{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asynq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asynq) ProtoMessage() {}

func (x *Asynq) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asynq.ProtoReflect.Descriptor instead.
func (*Asynq) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Asynq) GetRedis() *Asynq_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Asynq) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MaxSize       int32                  `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxBackups    int32                  `protobuf:"varint,4,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAge        int32                  `protobuf:"varint,5,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Compress      bool                   `protobuf:"varint,6,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Log) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Log) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Log) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Log) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

type Monitor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monitor) Reset() {
	*x = Monitor{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monitor) ProtoMessage() {}

func (x *Monitor) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monitor.ProtoReflect.Descriptor instead.
func (*Monitor) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Monitor) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Monitor) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Monitor) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type RabbitMQ_Listener struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Simple        *RabbitMQ_Listener_Simple `protobuf:"bytes,1,opt,name=simple,proto3" json:"simple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RabbitMQ_Listener) Reset() {
	*x = RabbitMQ_Listener{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RabbitMQ_Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RabbitMQ_Listener) ProtoMessage() {}

func (x *RabbitMQ_Listener) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RabbitMQ_Listener.ProtoReflect.Descriptor instead.
func (*RabbitMQ_Listener) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RabbitMQ_Listener) GetSimple() *RabbitMQ_Listener_Simple {
	if x != nil {
		return x.Simple
	}
	return nil
}

type RabbitMQ_Topic struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActivitySkuStockZero string                 `protobuf:"bytes,1,opt,name=activity_sku_stock_zero,json=activitySkuStockZero,proto3" json:"activity_sku_stock_zero,omitempty"`
	SendAward            string                 `protobuf:"bytes,2,opt,name=send_award,json=sendAward,proto3" json:"send_award,omitempty"`
	SendRebate           string                 `protobuf:"bytes,3,opt,name=send_rebate,json=sendRebate,proto3" json:"send_rebate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RabbitMQ_Topic) Reset() {
	*x = RabbitMQ_Topic{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RabbitMQ_Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RabbitMQ_Topic) ProtoMessage() {}

func (x *RabbitMQ_Topic) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RabbitMQ_Topic.ProtoReflect.Descriptor instead.
func (*RabbitMQ_Topic) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RabbitMQ_Topic) GetActivitySkuStockZero() string {
	if x != nil {
		return x.ActivitySkuStockZero
	}
	return ""
}

func (x *RabbitMQ_Topic) GetSendAward() string {
	if x != nil {
		return x.SendAward
	}
	return ""
}

func (x *RabbitMQ_Topic) GetSendRebate() string {
	if x != nil {
		return x.SendRebate
	}
	return ""
}

type RabbitMQ_Listener_Simple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefetch      int32                  `protobuf:"varint,1,opt,name=prefetch,proto3" json:"prefetch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RabbitMQ_Listener_Simple) Reset() {
	*x = RabbitMQ_Listener_Simple{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RabbitMQ_Listener_Simple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RabbitMQ_Listener_Simple) ProtoMessage() {}

func (x *RabbitMQ_Listener_Simple) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RabbitMQ_Listener_Simple.ProtoReflect.Descriptor instead.
func (*RabbitMQ_Listener_Simple) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *RabbitMQ_Listener_Simple) GetPrefetch() int32 {
	if x != nil {
		return x.Prefetch
	}
	return 0
}

type Data_Mysql struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxOpenConns  int32                  `protobuf:"varint,2,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	MaxIdleConns  int32                  `protobuf:"varint,3,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxLifeTime   *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_life_time,json=maxLifeTime,proto3" json:"max_life_time,omitempty"`
	MaxIdleTime   *durationpb.Duration   `protobuf:"bytes,5,opt,name=max_idle_time,json=maxIdleTime,proto3" json:"max_idle_time,omitempty"`
	DbCount       int32                  `protobuf:"varint,6,opt,name=db_count,json=dbCount,proto3" json:"db_count,omitempty"`
	TbCount       int32                  `protobuf:"varint,7,opt,name=tb_count,json=tbCount,proto3" json:"tb_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Mysql) Reset() {
	*x = Data_Mysql{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Mysql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Mysql) ProtoMessage() {}

func (x *Data_Mysql) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Mysql.ProtoReflect.Descriptor instead.
func (*Data_Mysql) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Data_Mysql) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_Mysql) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Mysql) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Mysql) GetMaxLifeTime() *durationpb.Duration {
	if x != nil {
		return x.MaxLifeTime
	}
	return nil
}

func (x *Data_Mysql) GetMaxIdleTime() *durationpb.Duration {
	if x != nil {
		return x.MaxIdleTime
	}
	return nil
}

func (x *Data_Mysql) GetDbCount() int32 {
	if x != nil {
		return x.DbCount
	}
	return 0
}

func (x *Data_Mysql) GetTbCount() int32 {
	if x != nil {
		return x.TbCount
	}
	return 0
}

type Data_Redis struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Host           string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port           int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Db             int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	PoolSize       int32                  `protobuf:"varint,4,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	MinIdleSize    int32                  `protobuf:"varint,5,opt,name=min_idle_size,json=minIdleSize,proto3" json:"min_idle_size,omitempty"`
	IdleTimeout    int32                  `protobuf:"varint,6,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	ConnectTimeout int32                  `protobuf:"varint,7,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	RetryAttempts  int32                  `protobuf:"varint,8,opt,name=retry_attempts,json=retryAttempts,proto3" json:"retry_attempts,omitempty"`
	RetryInterval  int32                  `protobuf:"varint,9,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"`
	PingInterval   int32                  `protobuf:"varint,10,opt,name=ping_interval,json=pingInterval,proto3" json:"ping_interval,omitempty"`
	KeepAlive      bool                   `protobuf:"varint,11,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Data_Redis) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Data_Redis) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *Data_Redis) GetMinIdleSize() int32 {
	if x != nil {
		return x.MinIdleSize
	}
	return 0
}

func (x *Data_Redis) GetIdleTimeout() int32 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

func (x *Data_Redis) GetConnectTimeout() int32 {
	if x != nil {
		return x.ConnectTimeout
	}
	return 0
}

func (x *Data_Redis) GetRetryAttempts() int32 {
	if x != nil {
		return x.RetryAttempts
	}
	return 0
}

func (x *Data_Redis) GetRetryInterval() int32 {
	if x != nil {
		return x.RetryInterval
	}
	return 0
}

func (x *Data_Redis) GetPingInterval() int32 {
	if x != nil {
		return x.PingInterval
	}
	return 0
}

func (x *Data_Redis) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

type Asynq_Redis struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Host           string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port           int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Db             int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	PoolSize       int32                  `protobuf:"varint,4,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	MinIdleSize    int32                  `protobuf:"varint,5,opt,name=min_idle_size,json=minIdleSize,proto3" json:"min_idle_size,omitempty"`
	IdleTimeout    int32                  `protobuf:"varint,6,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	ConnectTimeout int32                  `protobuf:"varint,7,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	RetryAttempts  int32                  `protobuf:"varint,8,opt,name=retry_attempts,json=retryAttempts,proto3" json:"retry_attempts,omitempty"`
	RetryInterval  int32                  `protobuf:"varint,9,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"`
	PingInterval   int32                  `protobuf:"varint,10,opt,name=ping_interval,json=pingInterval,proto3" json:"ping_interval,omitempty"`
	KeepAlive      bool                   `protobuf:"varint,11,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Asynq_Redis) Reset() {
	*x = Asynq_Redis{}
	mi := &file_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asynq_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asynq_Redis) ProtoMessage() {}

func (x *Asynq_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asynq_Redis.ProtoReflect.Descriptor instead.
func (*Asynq_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Asynq_Redis) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Asynq_Redis) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Asynq_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Asynq_Redis) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *Asynq_Redis) GetMinIdleSize() int32 {
	if x != nil {
		return x.MinIdleSize
	}
	return 0
}

func (x *Asynq_Redis) GetIdleTimeout() int32 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

func (x *Asynq_Redis) GetConnectTimeout() int32 {
	if x != nil {
		return x.ConnectTimeout
	}
	return 0
}

func (x *Asynq_Redis) GetRetryAttempts() int32 {
	if x != nil {
		return x.RetryAttempts
	}
	return 0
}

func (x *Asynq_Redis) GetRetryInterval() int32 {
	if x != nil {
		return x.RetryInterval
	}
	return 0
}

func (x *Asynq_Redis) GetPingInterval() int32 {
	if x != nil {
		return x.PingInterval
	}
	return 0
}

func (x *Asynq_Redis) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xad\x02\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x120\n" +
	"\brabbitmq\x18\x02 \x01(\v2\x14.kratos.api.RabbitMQR\brabbitmq\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.kratos.api.DataR\x04data\x12'\n" +
	"\x05asynq\x18\x04 \x01(\v2\x11.kratos.api.AsynqR\x05asynq\x12!\n" +
	"\x03log\x18\x05 \x01(\v2\x0f.kratos.api.LogR\x03log\x12!\n" +
	"\x03dcc\x18\x06 \x01(\v2\x0f.kratos.api.DccR\x03dcc\x12-\n" +
	"\amonitor\x18\a \x01(\v2\x13.kratos.api.MonitorR\amonitor\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xd1\x03\n" +
	"\bRabbitMQ\x12\x1c\n" +
	"\taddresses\x18\x01 \x01(\tR\taddresses\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x129\n" +
	"\blistener\x18\x05 \x01(\v2\x1d.kratos.api.RabbitMQ.ListenerR\blistener\x120\n" +
	"\x05topic\x18\x06 \x01(\v2\x1a.kratos.api.RabbitMQ.TopicR\x05topic\x1an\n" +
	"\bListener\x12<\n" +
	"\x06simple\x18\x01 \x01(\v2$.kratos.api.RabbitMQ.Listener.SimpleR\x06simple\x1a$\n" +
	"\x06Simple\x12\x1a\n" +
	"\bprefetch\x18\x01 \x01(\x05R\bprefetch\x1a~\n" +
	"\x05Topic\x125\n" +
	"\x17activity_sku_stock_zero\x18\x01 \x01(\tR\x14activitySkuStockZero\x12\x1d\n" +
	"\n" +
	"send_award\x18\x02 \x01(\tR\tsendAward\x12\x1f\n" +
	"\vsend_rebate\x18\x03 \x01(\tR\n" +
	"sendRebate\"\x85\x06\n" +
	"\x04Data\x12,\n" +
	"\x05mysql\x18\x01 \x01(\v2\x16.kratos.api.Data.MysqlR\x05mysql\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12$\n" +
	"\x04etcd\x18\x03 \x01(\v2\x10.kratos.api.EtcdR\x04etcd\x1a\x99\x02\n" +
	"\x05Mysql\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x12$\n" +
	"\x0emax_open_conns\x18\x02 \x01(\x05R\fmaxOpenConns\x12$\n" +
	"\x0emax_idle_conns\x18\x03 \x01(\x05R\fmaxIdleConns\x12=\n" +
	"\rmax_life_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vmaxLifeTime\x12=\n" +
	"\rmax_idle_time\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vmaxIdleTime\x12\x19\n" +
	"\bdb_count\x18\x06 \x01(\x05R\adbCount\x12\x19\n" +
	"\btb_count\x18\a \x01(\x05R\atbCount\x1a\xde\x02\n" +
	"\x05Redis\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12\x1b\n" +
	"\tpool_size\x18\x04 \x01(\x05R\bpoolSize\x12\"\n" +
	"\rmin_idle_size\x18\x05 \x01(\x05R\vminIdleSize\x12!\n" +
	"\fidle_timeout\x18\x06 \x01(\x05R\vidleTimeout\x12'\n" +
	"\x0fconnect_timeout\x18\a \x01(\x05R\x0econnectTimeout\x12%\n" +
	"\x0eretry_attempts\x18\b \x01(\x05R\rretryAttempts\x12%\n" +
	"\x0eretry_interval\x18\t \x01(\x05R\rretryInterval\x12#\n" +
	"\rping_interval\x18\n" +
	" \x01(\x05R\fpingInterval\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\v \x01(\bR\tkeepAlive\"Y\n" +
	"\x04Etcd\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"j\n" +
	"\x03Dcc\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\x01 \x01(\x05R\trateLimit\x12%\n" +
	"\x0eenable_degrade\x18\x02 \x01(\bR\renableDegrade\x12\x1d\n" +
	"\n" +
	"black_list\x18\x03 \x01(\tR\tblackList\"\xb9\x03\n" +
	"\x05Asynq\x12-\n" +
	"\x05redis\x18\x01 \x01(\v2\x17.kratos.api.Asynq.RedisR\x05redis\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x05R\vconcurrency\x1a\xde\x02\n" +
	"\x05Redis\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12\x1b\n" +
	"\tpool_size\x18\x04 \x01(\x05R\bpoolSize\x12\"\n" +
	"\rmin_idle_size\x18\x05 \x01(\x05R\vminIdleSize\x12!\n" +
	"\fidle_timeout\x18\x06 \x01(\x05R\vidleTimeout\x12'\n" +
	"\x0fconnect_timeout\x18\a \x01(\x05R\x0econnectTimeout\x12%\n" +
	"\x0eretry_attempts\x18\b \x01(\x05R\rretryAttempts\x12%\n" +
	"\x0eretry_interval\x18\t \x01(\x05R\rretryInterval\x12#\n" +
	"\rping_interval\x18\n" +
	" \x01(\x05R\fpingInterval\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\v \x01(\bR\tkeepAlive\"\xa8\x01\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x19\n" +
	"\bmax_size\x18\x03 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\x04 \x01(\x05R\n" +
	"maxBackups\x12\x17\n" +
	"\amax_age\x18\x05 \x01(\x05R\x06maxAge\x12\x1a\n" +
	"\bcompress\x18\x06 \x01(\bR\bcompress\"I\n" +
	"\aMonitor\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04pathB&Z$big-market-kratos/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),                // 0: kratos.api.Bootstrap
	(*Server)(nil),                   // 1: kratos.api.Server
	(*RabbitMQ)(nil),                 // 2: kratos.api.RabbitMQ
	(*Data)(nil),                     // 3: kratos.api.Data
	(*Etcd)(nil),                     // 4: kratos.api.Etcd
	(*Dcc)(nil),                      // 5: kratos.api.Dcc
	(*Asynq)(nil),                    // 6: kratos.api.Asynq
	(*Log)(nil),                      // 7: kratos.api.Log
	(*Monitor)(nil),                  // 8: kratos.api.Monitor
	(*Server_HTTP)(nil),              // 9: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),              // 10: kratos.api.Server.GRPC
	(*RabbitMQ_Listener)(nil),        // 11: kratos.api.RabbitMQ.Listener
	(*RabbitMQ_Topic)(nil),           // 12: kratos.api.RabbitMQ.Topic
	(*RabbitMQ_Listener_Simple)(nil), // 13: kratos.api.RabbitMQ.Listener.Simple
	(*Data_Mysql)(nil),               // 14: kratos.api.Data.Mysql
	(*Data_Redis)(nil),               // 15: kratos.api.Data.Redis
	(*Asynq_Redis)(nil),              // 16: kratos.api.Asynq.Redis
	(*durationpb.Duration)(nil),      // 17: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.rabbitmq:type_name -> kratos.api.RabbitMQ
	3,  // 2: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	6,  // 3: kratos.api.Bootstrap.asynq:type_name -> kratos.api.Asynq
	7,  // 4: kratos.api.Bootstrap.log:type_name -> kratos.api.Log
	5,  // 5: kratos.api.Bootstrap.dcc:type_name -> kratos.api.Dcc
	8,  // 6: kratos.api.Bootstrap.monitor:type_name -> kratos.api.Monitor
	9,  // 7: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	10, // 8: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	11, // 9: kratos.api.RabbitMQ.listener:type_name -> kratos.api.RabbitMQ.Listener
	12, // 10: kratos.api.RabbitMQ.topic:type_name -> kratos.api.RabbitMQ.Topic
	14, // 11: kratos.api.Data.mysql:type_name -> kratos.api.Data.Mysql
	15, // 12: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	4,  // 13: kratos.api.Data.etcd:type_name -> kratos.api.Etcd
	17, // 14: kratos.api.Etcd.timeout:type_name -> google.protobuf.Duration
	16, // 15: kratos.api.Asynq.redis:type_name -> kratos.api.Asynq.Redis
	17, // 16: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	17, // 17: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	13, // 18: kratos.api.RabbitMQ.Listener.simple:type_name -> kratos.api.RabbitMQ.Listener.Simple
	17, // 19: kratos.api.Data.Mysql.max_life_time:type_name -> google.protobuf.Duration
	17, // 20: kratos.api.Data.Mysql.max_idle_time:type_name -> google.protobuf.Duration
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
